name: Publish profile
on:
  push:
    branches: [main]
    paths:
      - profile/**
      - .github/workflows/publish-profile.yml
  workflow_dispatch:
concurrency:
  group: publish-profile
  cancel-in-progress: true
jobs:
  publish-profile:
    runs-on: ubuntu-latest
    environment:
      name: github-profile
      url: https://github.com/jcbhmr
    steps:
      - uses: actions/checkout@v3
      - run: |
          gh auth setup-git
          export GIT_DIR=$(mktemp -d)
          trap 'rm -rf "$GIT_DIR"' SIGINT SIGTERM ERR EXIT
          export GIT_WORK_TREE=profile
          git clone https://github.com/jcbhmr/jcbhmr "$GIT_DIR" --bare
          git config --unset core.bare
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit --allow-empty -m "Update profile $GITHUB_SHA"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PROFILE_TOKEN }}
