name: Publish profile/README.md
on:
  push:
    branches: [main]
    paths: [profile/**, .github/workflows/publish-profile.yml]
concurrency:
  group: publish-profile
  cancel-in-progress: true
jobs:
  publish-profile:
    environment:
      name: profile
      url: ${{ steps.push_profile.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: push_profile
        run: |
          set -e
          git remote add profile "https://$GITHUB_ACTOR:$GH_PROFILE_TOKEN@github.com/jcbhmr/jcbhmr.git"
          git subtree push -P profile profile main
          echo "page_url=https://github.com/jcbhmr" >> $GITHUB_OUTPUT
        env:
          GH_PROFILE_TOKEN: ${{ secrets.GH_PROFILE_TOKEN }}

