name: Publish profile/* to jcbhmr/jcbhmr
on:
  push:
    branches: [main]
    paths: [profile/**, .github/workflows/publish-profile.yml]
jobs:
  publish-profile:
    runs-on: ubuntu-latest
    environment:
      name: github-profile
      url: ${{ steps.split-push-profile-to-github-user-profile.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Split & push profile/ to GitHub user profile
        id: split-push-profile-to-github-user-profile
        run: |
          creds="$GITHUB_REPOSITORY_OWNER:$GITHUBX_TOKEN_PROFILE"
          github_repo="$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY_OWNER"
          git remote add profile "https://$creds@github.com/$github_repo.git"
          split_branch="$(git subtree split -P profile)"
          git push -f profile "$split_branch:main"
          echo "page_url=https://github.com/$github_repo" >> $GITHUB_OUTPUT
        env:
          GITHUBX_TOKEN_PROFILE: ${{ secrets.GITHUBX_TOKEN_PROFILE }}
