name: Publish profile
on:
  push:
    branches: [main]
    paths: [profile/**, .github/workflows/publish-profile.yml]
concurrency:
  group: publish-profile
  cancel-in-progress: true
jobs:
  publish-profile:
    runs-on: ubuntu-latest
    environment:
      name: github-profile
      url: https://github.com/jcbhmr
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
        env:
          # Expires on Dec 31, 2023
          PROFILE_GITHUB_TOKEN: ${{ secrets.PROFILE_GITHUB_TOKEN }}
      - run: |
          ref="$(git subtree split -P profile)"
          remote="https://jcbhmr:$PROFILE_GITHUB_TOKEN@github.com/jcbhmr/jcbhmr.git"
          git push -f "$remote" "$ref:main"
