# This GitHub Action workflow is triggered on a push event to the main branch
# and when the paths profile/** or {this file} are modified. The workflow runs
# on the ubuntu-latest runner and is given an environment with a name and URL.
# The workflow has a single job with a number of steps.
#
# 1. Check out the code.
# 2. Split the profile directory into a new branch using git subtree split.
# 3. Push the new branch to a remote repository, printing the repository's URL
#     to the workflow output. This step requires the GITHUBX_TOKEN_PROFILE
#     secret and uses the output of the git subtree split step as the BRANCH_REF
#     environment variable.
name: Publish profile/ to GitHub user profile
on:
  push:
    branches: [main]
    paths:
      - profile/**
      - .github/workflows/publish-profile-to-github-user-profile.yml
jobs:
  publish-profile-to-github-user-profile:
    runs-on: ubuntu-latest
    environment:
      name: github-profile
      url: ${{ steps.git-push.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: git subtree split
        id: git-subtree-split
        run: |
          branch_ref="$(git subtree split -P profile)"
          echo "branch_ref=$branch_ref" >> $GITHUB_OUTPUT
      - name: git push
        id: git-push
        run: |
          creds="$GITHUB_REPOSITORY_OWNER:$GITHUBX_TOKEN_PROFILE"
          slug="$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY_OWNER"

          git remote add profile "https://$creds@github.com/$slug.git"
          git push -f profile "$BRANCH_REF:main"

          page_url="https://github.com/$GITHUB_REPOSITORY_OWNER"
          echo "page_url=$page_url" >> $GITHUB_OUTPUT
        env:
          # Expires on Sun, Apr 9 2023
          GITHUBX_TOKEN_PROFILE: ${{ secrets.GITHUBX_TOKEN_PROFILE }}
          BRANCH_REF: ${{ steps.git-subtree-split.outputs.branch_ref }}
