name: Publish profile
on:
  push:
    branches: [main]
    paths:
      - profile/**
      - .github/workflows/publish-profile.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish-profile:
    runs-on: ubuntu-latest
    environment:
      name: github-profile
      url: https://github.com/jcbhmr
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PROFILE_DEPLOY_KEY }}
      - run: |
          export GIT_DIR=$(mktemp -d)
          trap 'rm -rf "$GIT_DIR"' SIGINT SIGTERM ERR EXIT
          export GIT_WORK_TREE=profile
          git clone git@github.com:jcbhmr/jcbhmr.git "$GIT_DIR" --bare
          git config --unset core.bare
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A
          git commit --allow-empty -m "Update profile $GITHUB_SHA"
          git push origin main
