name: Publish profile
on:
  push:
    branches: [main]
    paths: [profile/**, .github/workflows/publish-profile.yml]
concurrency:
  group: publish-profile
  cancel-in-progress: true
jobs:
  publish-profile:
    runs-on: ubuntu-latest
    environment:
      name: github-profile
      url: https://github.com/jcbhmr
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          ref="$(git subtree split -P profile)"
          remote="https://x:$GITHUBX_TOKEN_PROFILE@github.com/jcbhmr/jcbhmr.git"
          git push -f "$remote" "$ref:main"
        env:
          # Expires on Sun, Apr 9 2023
          GITHUBX_TOKEN_PROFILE: ${{ secrets.GITHUBX_TOKEN_PROFILE }}
