name: Pull jcbhmr/awesome-workflow-templates
on:
  push:
    branches: main
    paths: .github/workflows/pull-awesome-workflow-templates.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  pull-awesome-workflow-templates:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: jcbhmr/awesome-workflow-templates
          path: ../awesome-workflow-templates
      - run: rsync -av --del ../awesome-workflow-templates/workflow-templates/ workflow-templates/
      - uses: EndBug/add-and-commit@v9
        with:
          message: '[skip actions] Pull jcbhmr/awesome-workflow-templates'
