name: Update user secrets
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/update-user-secrets.yml
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
concurrency:
  group: update-user-secrets
  cancel-in-progress: true
jobs:
  update-user-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: jcbhmr/set-secrets-action@main
        with:
          token: ${{ secrets.USER_SECRETS_PAT }}
          query: user:${{ github.repository_owner }}
          secrets: ${{ toJSON(secrets) }}
          secret-filter: (k) => k !== "PROFILE_PAT"
